export enum HistoryType {
  HISTORY_INITIAL = 0,
  HISTORY_FIXEDSIZE_FRIENDLY_NAME = 1,
  HISTORY_COMPRESSION = 2,
  HISTORY_RECORDED_TIMESTAMP = 3,
  HISTORY_STREAM_CHUNK_TIMES = 4,
  HISTORY_FRIENDLY_NAME_ENCODING = 5,
  HISTORY_ENCRYPTION = 6,
}
